nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3000/']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_credentials: true
            allow_headers: ['*']
            max_age: 3600
        '^/':
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_credentials: true
            allow_headers: ['*']
            max_age: 3600