version: '3'
services:
     # Maria db database container
     db:
         image: mariadb
         container_name: mariadb
         restart: always
         volumes:
             - db-data:/var/lib/mysql
         environment:
             MYSQL_ROOT_PASSWORD: 'password'
             MYSQL_USER: 'maria'
             MYSQL_PASSWORD: 'password'
         ports:
           - "3306:3306"
         networks:
             - dev-environment

     # Symfony apache project container
     www:
         build: 
           context: .
           dockerfile: docker/php/Dockerfile
         container_name: php
         ports:
           - "8741:8000"
         volumes:
             - ./docker/php/vhosts:/etc/apache2/sites-enabled
             - ./:/var/www
         environment:
             DATABASE_URL: 'mysql://root:password@db:3306/app?serverVersion=16&charset=utf8'
         restart: always
         networks:
             - dev-environment

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  dev-environment:

volumes:
  db-data:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
