
services:
    # Maria db database container
    db:
        image: mariadb
        container_name: mariadb
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'maria'
            MYSQL_PASSWORD: 'password'
        ports:
          - "3306:3306"
        networks:
            - dev-environment

    # Symfony apache project container
    www:
        build: 
          context: .
          dockerfile: docker/php/Dockerfile
        container_name: php
        ports:
          - "8741:8000"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        environment:
            DATABASE_URL: 'mysql://root:password@db:3306/app?serverVersion=16&charset=utf8'
        restart: always
        networks:
            - dev-environment


networks:
    dev-environment:

volumes:
    db-data:

